src/vox/AdminBundle/Entity/Image.php
<?php

namespace vox\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */

class Image
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private  $id;


    private $file;

    private $temp;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private  $path;



    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }



    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }


    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
        // check if we have an old image path
        if (isset($this->path)) {
            // store the old name to delete after the update
            $this->temp = $this->path;
            $this->path = null;
        } else {
            $this->path = 'initial';
        }
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if (null !== $this->getFile()) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->path = $filename.'.'.$this->getFile()->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null === $this->getFile()) {
            return;
        }

        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->getFile()->move($this->getUploadRootDir(), $this->path);

        // check if we have an old image
        if (isset($this->temp)) {
            // delete the old image
            unlink($this->getUploadRootDir().'/'.$this->temp);
            // clear the temp image path
            $this->temp = null;
        }
        $this->file = null;
    }





    public function getAbsolutePath()
    {
        return null === $this->path
            ? null
            : $this->getUploadRootDir().'/'.$this->path;
    }

    public function getWebPath()
    {
        return null === $this->path
            ? null
            : $this->getUploadDir().'/'.$this->path;
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    protected function getUploadDir()
    {
        return 'uploads/img';
    }



    /**
     * Pre remove upload
     *
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        $this->temp = $this->getAbsolutePath();
    }

    /**
     * Remove upload
     *
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if ($this->temp) {
            unlink($this->temp);
        }
    }


}

src/vox/AdminBundle/Entity/MusicRelease.php
<?php

namespace vox\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * MusicReleaseEntity
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class MusicRelease
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="catalog", type="string", length=255)
     */
    private $catalog;

    /**
     * @var string
     *
     * @ORM\Column(name="format", type="string", length=255)
     */
    private $format;

    /**
     * @var string
     *
     * @ORM\Column(name="tracklist", type="text", nullable= true)
     */
    private $tracklist;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable= true)
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="shop_link", type="text", nullable= true)
     */
    private $shopLink;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_added", type="datetime", nullable= true)
     */
    private $dateAdded;

    /**
     * @var \Date
     *
     * @ORM\Column(name="release_date", type="date", nullable= true)
     */
    private $releaseDate;

    /**
     * @var boolean
     *
     * @ORM\Column(name="enabled", type="boolean")
     */
    private $enabled;

    /**
     * @ORM\OneToOne(targetEntity="vox\AdminBundle\Entity\Image", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $image = null;



    public function __construct() {
        $this->dateAdded = new \DateTime();
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return ReleaseEntity
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }


    /**
     * Set catalog
     *
     * @param string $catalog
     * @return ReleaseEntity
     */
    public function setCatalog($catalog)
    {
        $this->catalog = $catalog;

        return $this;
    }

    /**
     * Get catalog
     *
     * @return string
     */
    public function getCatalog()
    {
        return $this->catalog;
    }

    /**
     * Set format
     *
     * @param string $format
     * @return ReleaseEntity
     */
    public function setFormat($format)
    {
        $this->format = $format;

        return $this;
    }

    /**
     * Get format
     *
     * @return string
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * Set tracklist
     *
     * @param string $tracklist
     * @return ReleaseEntity
     */
    public function setTracklist($tracklist)
    {
        $this->tracklist = $tracklist;

        return $this;
    }

    /**
     * Get tracklist
     *
     * @return string 
     */
    public function getTracklist()
    {
        return $this->tracklist;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return ReleaseEntity
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }


    /**
     * Set shopLink
     *
     * @param string $shopLink
     * @return ReleaseEntity
     */
    public function setShopLink($shopLink)
    {
        $this->shopLink = $shopLink;

        return $this;
    }

    /**
     * Get shopLink
     *
     * @return string
     */
    public function getShopLink()
    {
        return $this->shopLink;
    }

    /**
     * Set dateAdded
     *
     * @param \Date $dateAdded
     * @return ReleaseEntity
     */
    public function setDateAdded($dateAdded)
    {
        $this->dateAdded = $dateAdded;

        return $this;
    }

    /**
     * Get dateAdded
     *
     * @return \Date
     */
    public function getDateAdded()
    {
        return $this->dateAdded;
    }

    /**
     * Set releaseDate
     *
     * @param \DateTime $releaseDate
     * @return ReleaseEntity
     */
    public function setReleaseDate($releaseDate)
    {
        $this->releaseDate = $releaseDate;

        return $this;
    }

    /**
     * Get releaseDate
     *
     * @return \DateTime
     */
    public function getReleaseDate()
    {
        return $this->releaseDate;
    }

    /**
     * Set enabled
     *
     * @param boolean $enabled
     * @return ReleaseEntity
     */
    public function setEnabled($enabled)
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * Get enabled
     *
     * @return boolean 
     */
    public function getEnabled()
    {
        return $this->enabled;
    }



    public function getImage()
    {
        return $this->image;
    }


    public function setImage(Image $image = null)
    {
        $this->image = $image;
    }



}

src/vox/AdminBundle/Form/MusicReleaseType.php
<?php

namespace vox\AdminBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class MusicReleaseType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            /*->add('artist_name',      'text', array('attr' => array('class' => 'form-control', 'autocomplete' => 'off')))*/
            ->add('title',     'text', array('attr' => array('class' => 'form-control', 'autocomplete' => 'off')))
            ->add('catalog',     'text', array('attr' => array('class' => 'form-control', 'autocomplete' => 'off')))
            ->add('format',     'text', array('attr' => array('class' => 'form-control', 'autocomplete' => 'off')))
            ->add('tracklist',    'textarea', array('attr' => array('class' => 'form-control'), 'required' => false))
            ->add('description',   'textarea', array('attr' => array('class' => 'form-control', 'rows' => 7), 'required' => false))
            ->add('shopLink',    'text', array('attr' => array('class' => 'form-control'), 'required' => false))
            ->add('release_date',   'date', array(
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'required' => false
            ), array('attr' => array('class' => 'form-control')))
            ->add('image', new ImageType(), array('required' => false))
            ->add('enabled', 'checkbox', array('required' => false, 'attr' => array('checked' => 'checked')))
            ->add('save',      'submit', array('attr' => array('class' => 'btn btn-default')))
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'vox\AdminBundle\Entity\MusicRelease'
        ));
    }

    public function getName()
    {
        return 'vox_musicrelease_form';
    }

} 

src/vox/AdminBundle/Controller/MusicReleaseController.php
<?php

namespace vox\AdminBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use vox\AdminBundle\Entity\MusicRelease;
use vox\AdminBundle\Form\MusicReleaseType;
use Symfony\Component\HttpFoundation\Request;

class MusicReleaseController extends Controller
{
    /**
     * @Route("/admin/releases", name="release_index")
     * @Template("")
     */
    public function release_indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $repository = $em->getRepository('voxAdminBundle:MusicRelease');

        $listReleases = $repository->findBy(array(), array('releaseDate' => 'DESC'));

        return array('listReleases' => $listReleases);
    }

    /**
     * @Route("/admin/add_release", name="release_add")
     * @Template("")
     */

    public function release_addAction(Request $request)
    {
        $music_release = new MusicRelease();
        $form = $this->get('form.factory')->create(new MusicReleaseType(), $music_release);

        if ($form->handleRequest($request)->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($music_release);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Release saved.');

            return $this->redirect($this->generateUrl('release_index'));
        }


        return array('form' => $form->createView());
    }


    /**
     * @Route("/admin/edit_release/{id}", name="release_edit")
     * @Template("")
     */

    public function release_editAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $repository = $em->getRepository('voxAdminBundle:MusicRelease');

        $release = $repository->find($id);

        $form = $this->get('form.factory')->create(new MusicReleaseType(), $release);

        if ($form->handleRequest($request)->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($release);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Release edited.');

            return $this->redirect($this->generateUrl('release_index'));
        }


        return array('form' => $form->createView(), 'img' => $release->getImage());
    }

    /**
     * @Route("/admin/release_delete/{id}", name="release_delete")
     * @Template("")
     */

    public function release_deleteAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $repository = $em->getRepository('voxAdminBundle:MusicRelease');

        $release = $repository->find($id);

        $em->remove($release);
        $em->flush();

        $request->getSession()->getFlashBag()->add('notice', 'Release deleted.');

        return $this->redirect($this->generateUrl('release_index'));
    }
}

src/vox/AdminBundle/Resources/views/MusicRelease/release_add.html.twig
{% extends "voxAdminBundle::main.html.twig" %}

{% block title %}New Release{% endblock %}
{% block breadcrumb %}
    <li><a href="{{ path("dashboard_index") }}">Home</a></li>
    <li><a href="{{ path("release_index") }}">Releases</a></li>
    <li class="active">New release</li>
{% endblock %}



{% block content %}

    {#{{ form(form) }}#}
    <div class="panel panel-default">
        <div class="panel-body">
            {{ form_start(form) }}


            <div class="form-group">
                <label>Title: </label>
                {{ form_widget(form.title) }}
            </div>
            <div class="form-group">
                <label>Catalog: </label>
                {{ form_widget(form.catalog) }}
            </div>
            <div class="form-group">
                <label>Format: </label>
                {{ form_widget(form.format) }}
            </div>
            <div class="form-group">
                <label>Tracklist: </label>
                {{ form_widget(form.tracklist) }}
            </div>
            <div class="form-group">
                <label>Description: </label>
                {{ form_widget(form.description) }}
            </div>
            <div class="form-group">
                <label>Bandcamp Link: </label>
                {{ form_widget(form.shopLink) }}
            </div>

            <div class="form-group">
                <label>Release date: </label>
                {{ form_widget(form.release_date) }}
            </div>


            <div class="form-group">
                <label>Enable:
                    {{ form_widget(form.enabled) }}
                </label>
            </div>

            <img height="100" width="100" id="img" src="#" alt="" style="display: none;"/>

            <div class="form-group">
                <label>
                    {{ form_widget(form.image) }}
                </label>
            </div>




            {{ form_widget(form.save) }}
            {{ form_end(form) }}
        </div>
    </div>

{% endblock %}


{% block javascript %}

    {{ parent() }}

    {% javascripts
    '@voxAdminBundle/Resources/public/js/file-loader.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}


    <script type="text/javascript">
        $(document).ready(function () {
            $("input[type='date']").datepicker({
                dateFormat: 'yy-mm-dd'
            });
        });
    </script>

{% endblock %}

src/vox/AdminBundle/Resources/views/MusicRelease/release_edit.html.twig
{% extends "voxAdminBundle::main.html.twig" %}

{% block title %}Edit Release{% endblock %}
 {% block breadcrumb %}
     <li><a href="{{ path("dashboard_index") }}">Home</a></li>
     <li><a href="{{ path("release_index") }}">Releases</a></li>
     <li class="active">Edit release</li>
 {% endblock %}


{% block content %}

    <div class="panel panel-default">
        <div class="panel-body">


            {{ form_start(form) }}

            <div class="form-group">
                <label>Title: </label>
                {{ form_widget(form.title) }}
            </div>
            <div class="form-group">
                <label>Catalog: </label>
                {{ form_widget(form.catalog) }}
            </div>
            <div class="form-group">
                <label>Format: </label>
                {{ form_widget(form.format) }}
            </div>
            <div class="form-group">
                <label>Tracklist: </label>
                {{ form_widget(form.tracklist) }}
            </div>
            <div class="form-group">
                <label>Description: </label>
                {{ form_widget(form.description) }}
            </div>
            <div class="form-group">
                <label>Bandcamp Link: </label>
                {{ form_widget(form.shopLink) }}
            </div>

            <div class="form-group">
                <label>Release date: </label>
                {{ form_widget(form.release_date) }}
            </div>


            <div class="form-group">
                <label>Enable:
                    {{ form_widget(form.enabled) }}
                </label>
            </div>
            <img height="100" width="100" id="img" src="#" alt="" style="display: none;"/>

            {% if img.webPath is defined %}<img id="img-old" height="100" width="100" src="{{ asset(img.webPath) }}"
                                                alt=""/>{% endif %}
            <br>

            <div class="form-group">
                <label>
                    {{ form_widget(form.image) }}
                </label>
            </div>
            {{ form_widget(form.save) }}
            {{ form_end(form) }}
        </div>
    </div>

{% endblock %}



{% block javascript %}

    {{ parent() }}

    {% javascripts
    '@voxAdminBundle/Resources/public/js/file-loader.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}


    <script type="text/javascript">
        $(document).ready(function () {
            $("input[type='date']").datepicker({
                dateFormat: 'yy-mm-dd'
            });
        });
    </script>

{% endblock %}

src/vox/AdminBundle/Resources/views/MusicRelease/release_index.html.twig
{% extends "voxAdminBundle::main.html.twig" %}

{% block title %}Releases{% endblock %}

 {% block breadcrumb %}
     <li><a href="{{ path("dashboard_index") }}">Home</a></li>
     <li class="active">Releases</li>
 {% endblock %}


 {% block top_menu_buttons %}
     <a class="btn btn-default" href="{{ path('release_add') }}"><i class="fa fa-plus"></i> New Release</a>
 {% endblock %}

{% block content %}

    <div class="panel panel-default">
        <div class="panel-body no-padding">

            <table class="table table-striped">
                <thead>
                <th>Cover</th>
                <th>Title</th>
                <th>Catalog</th>
                <th>Format</th>
                <th>Description</th>
                <th>Release date</th>
                <th>Date Added</th>
                <th>Enabled</th>
                <th>Delete</th>
                <th>Edit</th>
                </thead>
                <tbody>

                {% for release in listReleases %}
                    <tr>
                        <td>
                            {% if release.image.webPath is defined %}<img height="50" width="50"
                                                                          src="{{ asset(release.image.webPath) }}"
                                                                          alt="{{ release.title }}"/>{% endif %}
                        </td>
                        <td>{{ release.title }}</td>
                        <td>{{ release.catalog }}</td>
                        <td>{{ release.format }}</td>
                        <td>{{ release.description | slice(0, 100) }}...</td>
                        <td>{{ release.releaseDate | date('Y-m-d') }}</td>
                        <td>{{ release.dateAdded | date('Y-m-d') }}</td>
                        <td>{{ release.enabled }}</td>
                        <td><a data-toggle=confirm href="{{ path('release_delete', {'id': release.id}) }}">Delete</a>
                        </td>
                        <td><a href="{{ path('release_edit', {'id': release.id}) }}">Edit</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>



{% endblock %}


{% block javascript %}

    {{ parent() }}

    {% javascripts
    '@voxAdminBundle/Resources/public/js/jquery-confirm.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}

    <script type="text/javascript">
        $("[data-toggle=confirm]").confirm();
    </script>

{% endblock %}